import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

const PRIMARY_TARGETS: Array<{
  label: string;
  medianR2: string;
  coverage: string;
}> = [
  { label: "Range", medianR2: "0.998", coverage: "91.9%" },
  { label: "Energy margin", medianR2: "0.991", coverage: "91.8%" },
  { label: "Slope capability", medianR2: "0.993", coverage: "85.6%" },
  { label: "Total mass", medianR2: "1.000", coverage: "92.0%" },
];

const CORRECTION_TARGETS: Array<{ label: string; r2: string }> = [
  { label: "Drawbar pull", r2: "0.965" },
  { label: "Driving torque", r2: "0.912" },
  { label: "Sinkage", r2: "0.913" },
];

export function AboutModelDialog({ children }: { children: React.ReactNode }) {
  return (
    <Dialog>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>About this prediction model</DialogTitle>
          <DialogDescription>
            How the per-design predictions and 90% intervals are produced.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5 text-sm leading-6">
          <section>
            <h3 className="font-medium text-[var(--color-foreground)]">
              What it predicts
            </h3>
            <p className="text-[var(--color-muted-foreground)]">
              For a candidate lunar micro-rover (12 design variables) and a
              chosen mission scenario, the tool predicts four performance
              metrics: range, end-of-mission energy margin, statically
              achievable slope, and total mass. Each prediction is reported as
              a median plus a calibrated 90% prediction interval.
            </p>
          </section>

          <section>
            <h3 className="font-medium text-[var(--color-foreground)]">
              Training data
            </h3>
            <p className="text-[var(--color-muted-foreground)]">
              40,000 candidate rovers were generated by Latin-Hypercube
              sampling over the 12-D design space and evaluated on four
              canonical lunar mission scenarios with a deterministic
              physics-based mission simulator. The simulator integrates a
              time-stepped traverse with a parametric mass model, a solar
              power / battery state-of-charge model, and a wheel-soil
              terramechanics model. The resulting corpus (≈32k feasible
              rows after motor-torque screening) is split 80/10/10 for
              training, validation, and test; results below are on the
              held-out test split.
            </p>
          </section>

          <section>
            <h3 className="font-medium text-[var(--color-foreground)]">
              Wheel–soil correction layer
            </h3>
            <p className="text-[var(--color-muted-foreground)]">
              Inside each mission, wheel forces are computed analytically with
              a Bekker–Wong model for speed, then a learned correction term
              shifts them toward the higher-fidelity Soil Contact Model (SCM)
              implemented in PyChrono. The correction was fit on 500
              wheel-level operating points evaluated under both models.
              Three XGBoost regressors learn the residuals (Δdrawbar pull,
              Δdriving torque, Δsinkage) from a 12-D feature vector
              (vertical load, slip, wheel geometry, soil parameters); they
              run in well under a millisecond per call so they can be
              composed inside the mission loop without changing simulator
              wall-clock noticeably.
            </p>
            <div className="mt-2 overflow-hidden rounded-md border">
              <table className="w-full text-xs">
                <thead className="bg-[var(--color-muted)] text-[var(--color-muted-foreground)]">
                  <tr>
                    <th className="px-3 py-1.5 text-left font-medium">
                      Wheel-level target
                    </th>
                    <th className="px-3 py-1.5 text-right font-medium">
                      Test R²
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {CORRECTION_TARGETS.map((row) => (
                    <tr key={row.label} className="border-t">
                      <td className="px-3 py-1.5">{row.label}</td>
                      <td className="px-3 py-1.5 text-right tabular-nums">
                        {row.r2}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section>
            <h3 className="font-medium text-[var(--color-foreground)]">
              Surrogate model
            </h3>
            <p className="text-[var(--color-muted-foreground)]">
              For each performance metric the tool fits three quantile
              XGBoost regressors at τ = 0.05, 0.50, and 0.95, giving a
              median prediction and a 90% prediction interval. Hyperparameters
              were tuned with Optuna on a squared-error baseline, then reused
              across the three quantile heads with the loss switched to
              pinball. The median heads land within 0.005 R² of the
              squared-error baseline on the test split.
            </p>
          </section>

          <section>
            <h3 className="font-medium text-[var(--color-foreground)]">
              Performance on the held-out test split
            </h3>
            <div className="mt-2 overflow-hidden rounded-md border">
              <table className="w-full text-xs">
                <thead className="bg-[var(--color-muted)] text-[var(--color-muted-foreground)]">
                  <tr>
                    <th className="px-3 py-1.5 text-left font-medium">
                      Target
                    </th>
                    <th className="px-3 py-1.5 text-right font-medium">
                      Median R²
                    </th>
                    <th className="px-3 py-1.5 text-right font-medium">
                      90% PI coverage
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {PRIMARY_TARGETS.map((row) => (
                    <tr key={row.label} className="border-t">
                      <td className="px-3 py-1.5">{row.label}</td>
                      <td className="px-3 py-1.5 text-right tabular-nums">
                        {row.medianR2}
                      </td>
                      <td className="px-3 py-1.5 text-right tabular-nums">
                        {row.coverage}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="mt-2 text-xs text-[var(--color-muted-foreground)]">
              Coverage is empirical, on the test split, after row-wise
              monotone repair of the (q05, q50, q95) triple. Three of the
              four targets land within ±2 pp of the 90% nominal; slope
              capability is slightly under-covered (the per-row interval
              width is small, around 2°, so the heads are a touch
              over-confident on the tails).
            </p>
          </section>

          <section>
            <h3 className="font-medium text-[var(--color-foreground)]">
              Limitations
            </h3>
            <ul className="list-disc space-y-1 pl-5 text-[var(--color-muted-foreground)]">
              <li>
                Predictions are valid inside the calibrated design space and
                the four canonical scenarios; out-of-range design inputs are
                rejected by the form.
              </li>
              <li>
                Real-flown rovers (e.g. Pragyan, Yutu-2, MoonRanger,
                Rashid-1) are recovered well on mass and slope capability,
                but range and energy margin are noisier because those rovers
                run mission profiles outside the canonical scenario set.
              </li>
              <li>
                The wheel-soil correction is learned from PyChrono SCM, not
                from physical lunar regolith data, so absolute accuracy is
                bounded by SCM&rsquo;s own validation envelope.
              </li>
            </ul>
          </section>
        </div>
      </DialogContent>
    </Dialog>
  );
}
